<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class NorvaStoreSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        $this->db->disableForeignKeyChecks();

        // Truncate tables first
        $this->db->table('users')->truncate();
        $this->db->table('game_categories')->truncate();
        $this->db->table('games')->truncate();
        $this->db->table('product_categories')->truncate();
        $this->db->table('products')->truncate();
        $this->db->table('payment_methods')->truncate();
        $this->db->table('banners')->truncate();
        $this->db->table('vouchers')->truncate();
        $this->db->table('settings')->truncate();

        // 1. Admin User
        $this->db->table('users')->insert([
            'name' => 'Administrator Norva',
            'username' => 'admin',
            'email' => 'admin@norvago.id',
            'phone' => '081234567890',
            'password' => password_hash('admin123', PASSWORD_BCRYPT),
            'role' => 'admin',
            'balance' => 1000000.00,
            'tier' => 'vip',
            'status' => 'active',
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        // Demo Reseller
        $this->db->table('users')->insert([
            'name' => 'John Reseller',
            'username' => 'reseller',
            'email' => 'reseller@norvago.id',
            'phone' => '089876543210',
            'password' => password_hash('member123', PASSWORD_BCRYPT),
            'role' => 'reseller',
            'balance' => 500000.00,
            'tier' => 'gold',
            'status' => 'active',
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        // 2. Game Categories
        $categories = [
            ['name' => 'Games Mobile', 'slug' => 'games-mobile', 'icon' => 'smartphone', 'sort_order' => 1, 'status' => 'active', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Games PC', 'slug' => 'games-pc', 'icon' => 'monitor', 'sort_order' => 2, 'status' => 'active', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Voucher', 'slug' => 'voucher', 'icon' => 'ticket', 'sort_order' => 3, 'status' => 'active', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Entertainment', 'slug' => 'entertainment', 'icon' => 'tv', 'sort_order' => 4, 'status' => 'active', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Pulsa & PLN', 'slug' => 'pulsa-pln', 'icon' => 'zap', 'sort_order' => 5, 'status' => 'active', 'created_at' => $now, 'updated_at' => $now],
        ];
        $this->db->table('game_categories')->insertBatch($categories);

        // 3. Games
        $games = [
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Mobile Legends: Bang Bang',
                'slug' => 'mobile-legends',
                'subtitle' => 'Moonton',
                'developer' => 'Moonton',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/games/mlbb.png',
                'banner_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/mlbb_banner.jpg',
                'instructions' => 'Untuk mengetahui User ID Anda, silakan klik menu profile di bagian kiri atas pada menu utama game. Contoh: 12345678 (1234). User ID adalah 12345678 dan Zone ID adalah 1234.',
                'target_input_type' => 'double',
                'target_input_label_1' => 'User ID',
                'target_input_label_2' => 'Zone ID',
                'target_input_placeholder_1' => 'Contoh: 12345678',
                'target_input_placeholder_2' => 'Contoh: 1234',
                'server_list' => null,
                'check_id_endpoint' => 'mlbb',
                'is_popular' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Free Fire',
                'slug' => 'free-fire',
                'subtitle' => 'Garena',
                'developer' => 'Garena',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/games/ff.png',
                'banner_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/ff_banner.jpg',
                'instructions' => 'Untuk menemukan Player ID Anda, klik avatar Anda di pojok kiri atas layar game. Player ID Anda akan terlihat di bawah nama panggilan Anda.',
                'target_input_type' => 'single',
                'target_input_label_1' => 'Player ID',
                'target_input_label_2' => null,
                'target_input_placeholder_1' => 'Masukkan Player ID (Contoh: 123456789)',
                'target_input_placeholder_2' => null,
                'server_list' => null,
                'check_id_endpoint' => 'ff',
                'is_popular' => 1,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'Genshin Impact',
                'slug' => 'genshin-impact',
                'subtitle' => 'HoYoverse',
                'developer' => 'HoYoverse',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/games/genshin.png',
                'banner_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/genshin_banner.jpg',
                'instructions' => 'Buka menu Paimon di pojok kiri atas. UID Anda tertera di bawah avatar profil karakter atau di pojok kanan bawah layar game.',
                'target_input_type' => 'server_dropdown',
                'target_input_label_1' => 'UID HoYoverse',
                'target_input_label_2' => 'Server',
                'target_input_placeholder_1' => 'Contoh: 812345678',
                'target_input_placeholder_2' => 'Pilih Server',
                'server_list' => json_encode([
                    ['code' => 'os_asia', 'name' => 'Asia'],
                    ['code' => 'os_usa', 'name' => 'America'],
                    ['code' => 'os_euro', 'name' => 'Europe'],
                    ['code' => 'os_cht', 'name' => 'TW / HK / MO'],
                ]),
                'check_id_endpoint' => 'genshin',
                'is_popular' => 1,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'category_id' => 2,
                'name' => 'Valorant',
                'slug' => 'valorant',
                'subtitle' => 'Riot Games',
                'developer' => 'Riot Games',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/games/valorant.png',
                'banner_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/val_banner.jpg',
                'instructions' => 'Masukkan Riot ID lengkap beserta Tagline. Contoh: NorvaGamer#IND',
                'target_input_type' => 'single',
                'target_input_label_1' => 'Riot ID & Tagline',
                'target_input_label_2' => null,
                'target_input_placeholder_1' => 'Contoh: Username#TAG',
                'target_input_placeholder_2' => null,
                'server_list' => null,
                'check_id_endpoint' => 'valorant',
                'is_popular' => 1,
                'is_active' => 1,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Honor of Kings',
                'slug' => 'honor-of-kings',
                'subtitle' => 'Level Infinite',
                'developer' => 'Tencent Games',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/games/hok.png',
                'banner_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/hok_banner.jpg',
                'instructions' => 'Buka profil game Anda, Player ID dapat disalin dari menu profile setting.',
                'target_input_type' => 'single',
                'target_input_label_1' => 'Player ID',
                'target_input_label_2' => null,
                'target_input_placeholder_1' => 'Masukkan Player ID HoK',
                'target_input_placeholder_2' => null,
                'server_list' => null,
                'check_id_endpoint' => 'hok',
                'is_popular' => 1,
                'is_active' => 1,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'PUBG Mobile',
                'slug' => 'pubg-mobile',
                'subtitle' => 'Tencent / Krafton',
                'developer' => 'Level Infinite',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/games/pubgm.png',
                'banner_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/pubg_banner.jpg',
                'instructions' => 'Buka profil akun game PUBG Mobile Anda di pojok kanan atas untuk melihat Nomor ID Karakter.',
                'target_input_type' => 'single',
                'target_input_label_1' => 'User ID Karakter',
                'target_input_label_2' => null,
                'target_input_placeholder_1' => 'Contoh: 5123456789',
                'target_input_placeholder_2' => null,
                'server_list' => null,
                'check_id_endpoint' => 'pubgm',
                'is_popular' => 1,
                'is_active' => 1,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        $this->db->table('games')->insertBatch($games);

        // 4. Product Categories (Denomination Groups)
        $prodCategories = [
            ['id' => 1, 'game_id' => 1, 'name' => 'Diamonds Fast Server', 'sort_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'game_id' => 1, 'name' => 'Membership & Pass', 'sort_order' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'game_id' => 2, 'name' => 'Diamonds Garena', 'sort_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'game_id' => 3, 'name' => 'Genesis Crystals & Blessing', 'sort_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'game_id' => 4, 'name' => 'Valorant Points (VP)', 'sort_order' => 1, 'created_at' => $now, 'updated_at' => $now],
        ];
        $this->db->table('product_categories')->insertBatch($prodCategories);

        // 5. Products (Denominations)
        $products = [
            // MLBB Products
            [
                'game_id' => 1,
                'category_id' => 1,
                'name' => '86 Diamonds (78+8 Bonus)',
                'sku' => 'MLBB-86',
                'provider_code' => 'manual',
                'provider_sku' => 'MLBB86',
                'price_cost' => 18500.00,
                'price_normal' => 20500.00,
                'price_gold' => 19500.00,
                'price_reseller' => 18800.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 1,
                'category_id' => 1,
                'name' => '172 Diamonds (156+16 Bonus)',
                'sku' => 'MLBB-172',
                'provider_code' => 'manual',
                'provider_sku' => 'MLBB172',
                'price_cost' => 37000.00,
                'price_normal' => 41000.00,
                'price_gold' => 39000.00,
                'price_reseller' => 37500.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 1,
                'category_id' => 1,
                'name' => '257 Diamonds (234+23 Bonus)',
                'sku' => 'MLBB-257',
                'provider_code' => 'manual',
                'provider_sku' => 'MLBB257',
                'price_cost' => 55000.00,
                'price_normal' => 61000.00,
                'price_gold' => 58000.00,
                'price_reseller' => 56000.00,
                'is_flash_sale' => 1,
                'flash_sale_price' => 57500.00,
                'flash_sale_end' => date('Y-m-d H:i:s', strtotime('+7 days')),
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 1,
                'category_id' => 1,
                'name' => '344 Diamonds',
                'sku' => 'MLBB-344',
                'provider_code' => 'manual',
                'provider_sku' => 'MLBB344',
                'price_cost' => 74000.00,
                'price_normal' => 81500.00,
                'price_gold' => 78000.00,
                'price_reseller' => 75000.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 1,
                'category_id' => 1,
                'name' => '706 Diamonds',
                'sku' => 'MLBB-706',
                'provider_code' => 'manual',
                'provider_sku' => 'MLBB706',
                'price_cost' => 148000.00,
                'price_normal' => 163000.00,
                'price_gold' => 156000.00,
                'price_reseller' => 150000.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 1,
                'category_id' => 2,
                'name' => 'Weekly Diamond Pass (WDP)',
                'sku' => 'MLBB-WDP',
                'provider_code' => 'manual',
                'provider_sku' => 'MLBBWDP',
                'price_cost' => 25000.00,
                'price_normal' => 27500.00,
                'price_gold' => 26500.00,
                'price_reseller' => 25500.00,
                'is_flash_sale' => 1,
                'flash_sale_price' => 26900.00,
                'flash_sale_end' => date('Y-m-d H:i:s', strtotime('+7 days')),
                'status' => 'available',
                'icon_url' => 'pass',
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 1,
                'category_id' => 2,
                'name' => 'Twilight Pass',
                'sku' => 'MLBB-TWILIGHT',
                'provider_code' => 'manual',
                'provider_sku' => 'MLBBTWILIGHT',
                'price_cost' => 135000.00,
                'price_normal' => 148000.00,
                'price_gold' => 142000.00,
                'price_reseller' => 137000.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'pass',
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Free Fire Products
            [
                'game_id' => 2,
                'category_id' => 3,
                'name' => '70 Diamonds',
                'sku' => 'FF-70',
                'provider_code' => 'manual',
                'provider_sku' => 'FF70',
                'price_cost' => 9000.00,
                'price_normal' => 10000.00,
                'price_gold' => 9500.00,
                'price_reseller' => 9200.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 2,
                'category_id' => 3,
                'name' => '140 Diamonds',
                'sku' => 'FF-140',
                'provider_code' => 'manual',
                'provider_sku' => 'FF140',
                'price_cost' => 18000.00,
                'price_normal' => 20000.00,
                'price_gold' => 19000.00,
                'price_reseller' => 18400.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 2,
                'category_id' => 3,
                'name' => '355 Diamonds',
                'sku' => 'FF-355',
                'provider_code' => 'manual',
                'provider_sku' => 'FF355',
                'price_cost' => 45000.00,
                'price_normal' => 50000.00,
                'price_gold' => 47500.00,
                'price_reseller' => 46000.00,
                'is_flash_sale' => 1,
                'flash_sale_price' => 47900.00,
                'flash_sale_end' => date('Y-m-d H:i:s', strtotime('+7 days')),
                'status' => 'available',
                'icon_url' => 'diamond',
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Genshin Impact
            [
                'game_id' => 3,
                'category_id' => 4,
                'name' => 'Blessing of the Welkin Moon',
                'sku' => 'GI-WELKIN',
                'provider_code' => 'manual',
                'provider_sku' => 'GIWELKIN',
                'price_cost' => 65000.00,
                'price_normal' => 73000.00,
                'price_gold' => 69000.00,
                'price_reseller' => 66500.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'welkin',
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 3,
                'category_id' => 4,
                'name' => '300+30 Genesis Crystals',
                'sku' => 'GI-330',
                'provider_code' => 'manual',
                'provider_sku' => 'GI330',
                'price_cost' => 65000.00,
                'price_normal' => 73000.00,
                'price_gold' => 69000.00,
                'price_reseller' => 66500.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'crystal',
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Valorant
            [
                'game_id' => 4,
                'category_id' => 5,
                'name' => '475 Valorant Points',
                'sku' => 'VAL-475',
                'provider_code' => 'manual',
                'provider_sku' => 'VAL475',
                'price_cost' => 47000.00,
                'price_normal' => 53000.00,
                'price_gold' => 50000.00,
                'price_reseller' => 48500.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'vp',
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'game_id' => 4,
                'category_id' => 5,
                'name' => '1000 Valorant Points',
                'sku' => 'VAL-1000',
                'provider_code' => 'manual',
                'provider_sku' => 'VAL1000',
                'price_cost' => 97000.00,
                'price_normal' => 108000.00,
                'price_gold' => 103000.00,
                'price_reseller' => 99500.00,
                'is_flash_sale' => 0,
                'flash_sale_price' => 0.00,
                'flash_sale_end' => null,
                'status' => 'available',
                'icon_url' => 'vp',
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        $this->db->table('products')->insertBatch($products);

        // 6. Payment Methods (Self-Hosted QRIS, BCA, Mandiri, DANA, Saldo Akun)
        $paymentMethods = [
            [
                'name' => 'QRIS Dinamis (All Payment Realtime)',
                'code' => 'qris_auto',
                'group_name' => 'QRIS Realtime',
                'type' => 'qris',
                'fee_flat' => 0.00,
                'fee_percent' => 0.00,
                'min_amount' => 1000.00,
                'max_amount' => 10000000.00,
                'icon_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/payments/qris.png',
                'account_number' => 'QRIS All Payment',
                'account_name' => 'NORVAGO MERCHANT',
                'instructions' => "1. Buka aplikasi E-Wallet (GoPay, OVO, DANA, ShopeePay, LinkAja) atau Mobile Banking (BCA, Mandiri, BRI, BNI, Jago, dll).\n2. Pilih menu Bayar / Scan QRIS.\n3. Scan Kode QRIS yang muncul di layar.\n4. Nominal akan otomatis terisi sesuai dengan total invoice termasuk kode unik.\n5. Masukkan PIN Anda dan konfirmasi pembayaran.\n6. Sistem akan otomatis memproses pesanan Anda dalam hitungan detik!",
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Transfer Bank BCA (Otomatis)',
                'code' => 'bca_auto',
                'group_name' => 'Bank Transfer',
                'type' => 'bank_transfer',
                'fee_flat' => 0.00,
                'fee_percent' => 0.00,
                'min_amount' => 10000.00,
                'max_amount' => 50000000.00,
                'icon_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/payments/bca.png',
                'account_number' => '1234567890',
                'account_name' => 'NORVAGO',
                'instructions' => "1. Transfer ke rekening BCA: 1234567890 a/n NORVAGO.\n2. Pastikan nominal transfer PERSIS sesuai total tagihan hingga 3 digit terakhir (kode unik).\n3. Pembayaran akan terverifikasi secara otomatis.",
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Transfer Bank Mandiri (Otomatis)',
                'code' => 'mandiri_auto',
                'group_name' => 'Bank Transfer',
                'type' => 'bank_transfer',
                'fee_flat' => 0.00,
                'fee_percent' => 0.00,
                'min_amount' => 10000.00,
                'max_amount' => 50000000.00,
                'icon_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/payments/mandiri.png',
                'account_number' => '1370012345678',
                'account_name' => 'NORVAGO',
                'instructions' => "1. Transfer ke rekening Mandiri: 1370012345678 a/n NORVAGO.\n2. Transfer tepat sesuai nominal hingga 3 digit terakhir.",
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'DANA Transfer (Otomatis)',
                'code' => 'dana_auto',
                'group_name' => 'E-Wallet',
                'type' => 'ewallet',
                'fee_flat' => 0.00,
                'fee_percent' => 0.00,
                'min_amount' => 5000.00,
                'max_amount' => 10000000.00,
                'icon_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/payments/dana.png',
                'account_number' => '081234567890',
                'account_name' => 'NORVAGO',
                'instructions' => "1. Buka aplikasi DANA -> Kirim Uang.\n2. Masukkan nomor HP: 081234567890.\n3. Masukkan nominal PERSIS hingga 3 digit terakhir kode unik.",
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Saldo Akun Member (Potong Saldo)',
                'code' => 'balance_instant',
                'group_name' => 'Saldo Member',
                'type' => 'balance',
                'fee_flat' => 0.00,
                'fee_percent' => 0.00,
                'min_amount' => 1000.00,
                'max_amount' => 50000000.00,
                'icon_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/payments/wallet.png',
                'account_number' => 'Internal Wallet',
                'account_name' => 'Saldo Akun',
                'instructions' => "1. Pembayaran akan dipotong langsung dari saldo akun Anda.\n2. Pesanan akan langsung diproses detik ini juga tanpa antre.",
                'status' => 'active',
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        $this->db->table('payment_methods')->insertBatch($paymentMethods);

        // 7. Banners
        $banners = [
            [
                'title' => 'Top Up Game Termurah & Tercepat 24 Jam',
                'subtitle' => 'Proses otomatis 1-5 detik langsung masuk ke akun game Anda!',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/banner1.jpg',
                'link_url' => '#games',
                'sort_order' => 1,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'title' => 'Flash Sale Mobile Legends & Free Fire',
                'subtitle' => 'Diskon spesial Weekly Diamond Pass dan Diamonds setiap hari.',
                'image_url' => 'https://res.cloudinary.com/norva-media/image/upload/v1/banners/banner2.jpg',
                'link_url' => '/order/mobile-legends',
                'sort_order' => 2,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        $this->db->table('banners')->insertBatch($banners);

        // 8. Vouchers
        $vouchers = [
            [
                'code' => 'NORVAGAMING',
                'name' => 'Diskon Pengguna Baru Rp 2.000',
                'type' => 'fixed',
                'amount' => 2000.00,
                'min_purchase' => 20000.00,
                'max_discount' => 2000.00,
                'quota' => 500,
                'used_count' => 0,
                'valid_until' => date('Y-m-d H:i:s', strtotime('+30 days')),
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'HEMAT5',
                'name' => 'Diskon 5% Semua Game',
                'type' => 'percent',
                'amount' => 5.00,
                'min_purchase' => 50000.00,
                'max_discount' => 10000.00,
                'quota' => 200,
                'used_count' => 0,
                'valid_until' => date('Y-m-d H:i:s', strtotime('+30 days')),
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        $this->db->table('vouchers')->insertBatch($vouchers);

        // 9. Web Settings
        $settings = [
            ['setting_key' => 'site_name', 'setting_value' => 'Norvago', 'setting_group' => 'general'],
            ['setting_key' => 'site_tagline', 'setting_value' => 'Top Up Game Cepat, Aman, & Otomatis 24 Jam', 'setting_group' => 'general'],
            ['setting_key' => 'site_description', 'setting_value' => 'Platform top up game online terpercaya nomor 1 di Indonesia dengan harga murah, proses instan 1-5 detik dan pembayaran QRIS All Payment.', 'setting_group' => 'general'],
            ['setting_key' => 'site_logo', 'setting_value' => '', 'setting_group' => 'general'],
            ['setting_key' => 'site_favicon', 'setting_value' => '', 'setting_group' => 'general'],
            ['setting_key' => 'whatsapp_cs', 'setting_value' => '6281234567890', 'setting_group' => 'contact'],
            ['setting_key' => 'instagram_url', 'setting_value' => 'https://instagram.com/norvastore', 'setting_group' => 'contact'],
            ['setting_key' => 'telegram_channel', 'setting_value' => 'https://t.me/norvastore', 'setting_group' => 'contact'],
            
            // Self-Hosted QRIS Settings
            // Standard Indonesian QRIS string template
            ['setting_key' => 'qris_static_payload', 'setting_value' => '00020101021126590013ID.CO.QRIS.WWW011893600998000000000002150000000000000000303UMI51440014ID.CO.QRIS.WWW02150000000000000000303UMI5204581253033605802ID5911NORVAGO6007JAKARTA61051234062070703A016304', 'setting_group' => 'qris'],
            ['setting_key' => 'qris_merchant_name', 'setting_value' => 'NORVAGO', 'setting_group' => 'qris'],
            ['setting_key' => 'qris_city', 'setting_value' => 'JAKARTA', 'setting_group' => 'qris'],
            ['setting_key' => 'webhook_secret_key', 'setting_value' => bin2hex(random_bytes(16)), 'setting_group' => 'qris'],
            ['setting_key' => 'order_expiry_minutes', 'setting_value' => '15', 'setting_group' => 'order'],
            ['setting_key' => 'auto_fulfill_provider', 'setting_value' => '1', 'setting_group' => 'provider'],
            ['setting_key' => 'provider_digiflazz_user', 'setting_value' => '', 'setting_group' => 'provider'],
            ['setting_key' => 'provider_digiflazz_key', 'setting_value' => '', 'setting_group' => 'provider'],
            ['setting_key' => 'provider_vip_api_id', 'setting_value' => '', 'setting_group' => 'provider'],
            ['setting_key' => 'provider_vip_api_key', 'setting_value' => '', 'setting_group' => 'provider'],
        ];
        $this->db->table('settings')->insertBatch($settings);

        $this->db->enableForeignKeyChecks();
    }
}
